### ISSUE TITLE
Crafting: cache not work

### ISSUE THREAD

**Issue by Blackjack200** [ApexieDevelopment/OpenTouch#10]
merge my fork
https://github.com/ApexieDevelopment/OpenTouch/blob/e59bfd2d51bca8d749d1a6f851da8d2caab701a2/src/pocketmine/inventory/CraftingManager.php#L125

**Comment by ItzLightyHD** [comment]
Ok, I'm merging it.

**Comment by ItzLightyHD** [comment]
https://github.com/ApexieDevelopment/OpenTouch/commit/2fc3a2d0d0e3256ae34a3c8ea0e10bf411b90a84
