### ISSUE TITLE
How fix it

### ISSUE THREAD

**Issue by Quaterizer** [ApexieDevelopment/OpenTouch#21]
ERROR] Composer dependencies and/or autoloader are out of sync.
[ERROR] - Current revision is 49511302dbe5fcbc5521b47175ca2e549c53e986
[ERROR] - Composer dependencies were last synchronized for revision ffc09cb75988
a86d2ae25911289c76ce37ec14df
[ERROR] Out-of-sync Composer dependencies may result in crashes and classes not
being found.
[ERROR] Please synchronize Composer dependencies before running the server.
Press any key to continue . . .

**Comment by ItzLightyHD** [comment]
Are you running it from source? If yes, then do:
```bash
composer update --no-dev
```
Then, run the server software as usual.
If you're running it from the phar, we'll see if we can fix this problem.

**Comment by ItzLightyHD** [comment]
I see it's my fault, I'm fixing it right now.

**Comment by ItzLightyHD** [comment]
Here we go, I fixed it; go to download the new phar from here: https://github.com/ApexieDevelopment/OpenTouch/releases/tag/1.0.5

**Comment by Quaterizer** [comment]
Thanks
