### ISSUE TITLE
1.17.10 bedrock version

### ISSUE THREAD

**Issue by Grannnnnnnnx** [ApexieDevelopment/OpenTouch#45]
please update the open touch to 1.17.10 
because my minecraft is 1.17.10

i hope you will notice me

i will thanks first

**Comment by ItzLightyHD** [comment]
Actually, OpenTouch 1.0.6 adds support for it: https://github.com/ApexieDevelopment/OpenTouch/releases/tag/1.0.6-pr1

**Comment by Grannnnnnnnx** [comment]
THank you so much
