### ISSUE TITLE
Why is these

### ISSUE THREAD

**Issue by Grannnnnnnnx** [ApexieDevelopment/OpenTouch#46]
``
![Screenshot_20210727-214340_PocketMine-MP](https://user-images.githubusercontent.com/86281625/127164782-f9ed53af-4c0a-461d-b983-cbc78da1f562.jpg)

**Comment by ItzLightyHD** [comment]
> 
> 
> ``
> ![Screenshot_20210727-214340_PocketMine-MP](https://user-images.githubusercontent.com/86281625/127164782-f9ed53af-4c0a-461d-b983-cbc78da1f562.jpg)

Because you need at least PHP 7.4 to run OpenTouch. I can't help you here, you need to submit an issue to the PocketMine-MP Android App developers to change the PHP binary to 7.4.

**Comment by Grannnnnnnnx** [comment]
In computer it work

**Comment by ItzLightyHD** [comment]
> 
> 
> In computer it work

It's normal because you have PHP 7.4 in the "bin" folder. On mobile there's nothing I can do for you since it needs to be fixed by the app creators :/
