### ISSUE TITLE
Too few arguments to function pocketmine\entity\Skin::__construct(), 2 passed in C:\Users\User\Desktop\BedwarsSolo2\plugins\BedwarsSolo\src\vixikhd\BedWarsSolo\BedWars.php on line 128 and at least 3 expected

### ISSUE THREAD

**Issue by SunshroomChan** [ApexieDevelopment/OpenTouch#61]
When i change into OpenTouch and it cause crash server on skin

And i don't know how playFabId is use for to add into my plugin code

My code is this 

public function getSkinFromFile($path){
        $img = imagecreatefrompng($path);
        $bytes = '';
        $l = (int) getimagesize($path)[1];
        for ($y = 0; $y < $l; $y++) {
            for ($x = 0; $x < 64; $x++) {
                $rgba = imagecolorat($img, $x, $y);
                $a = ((~((int)($rgba >> 24))) << 1) & 0xff;
                $r = ($rgba >> 16) & 0xff;
                $g = ($rgba >> 8) & 0xff;
                $b = $rgba & 0xff;
                $bytes .= chr($r) . chr($g) . chr($b) . chr($a);
            }
        }
        imagedestroy($img);
        return new Skin("Standard_CustomSlim", $bytes); 
    }

and it said error on line new Skin("Standard_CustomSlim", $bytes); 

Thanks for help

**Comment by ItzLightyHD** [comment]
That's because we are not using PocketMine's latest skin system. You need to fix your plugin first.
